### ISSUE TITLE
Support bills acceptor

### ISSUE THREAD

**Issue by iBobik** [samotari/bleskomat-diy#21]
Coins does not make sence for my use-case. I saw bills acceptor on some photos.

Does this project support it?
Are there some docs about it?

**Comment by chill117** [comment]
Hello. You are correct in that this repo does not currently include support for a bill acceptor. We may add support for it during the second half of this year, but no guarantees. Until then you are welcome to fork and extend this project with a bill acceptor of your own - there are a few options available from online marketplaces.

**Comment by chill117** [comment]
@iBobik Support for the NV10 (USB+) and NV9 bill acceptors has been added by 6105a40e6dd995de38533d95790aa5229d335d9b and will be included in a future release.

**Comment by chill117** [comment]
Closing because bill acceptor support was added.
