### ISSUE TITLE
Specify exact hardware to use

### ISSUE THREAD

**Issue by ArbenKarb** [samotari/bleskomat-diy#4]
ESP32 - m5stack core
Coin Acceptor - https://ehardware77.ecrater.com/p/7022788/multi-coin-acceptor-selector-programmable-6 ?
TFT Screen - built-in screen m5stack? 
Add Bill Acceptor?

**Comment by chill117** [comment]
Done! See [Hardware Requirements](https://github.com/samotari/bleskomat#hardware-requirements)
